### ISSUE TITLE
SetMultipartNumberMaximum used incorrectly

### ISSUE THREAD

**Issue by cmaster11** [beyondstorage/go-service-oss#50]
With the latest 2.2.0, the Go code does not compile against 386/arm architectures, with the error

```
../go/pkg/mod/github.com/beyondstorage/go-service-oss/v2@v2.2.0/storage.go:284:32: constant 5368709120 overflo
ws int
```

**Comment by Prnyself** [comment]
Oops, that's a typo which caused this error.

The method here should be `SetMultipartSizeMaximum`, which got an `int64` as an input param, instead of `SetMultipartNumberMaximum`, which got an `int` as an input param. It may be caused by auto-completion from IDE.

We'll fix it asap, and then release a new fixed version. After that we will notice you in this issue.

Sorry for this :(

**Comment by cmaster11** [comment]
Thanks for the fast fast fast reply :)

**Comment by Xuanwo** [comment]
Hi, @cmaster11 #52 has been merged, and we will release v2.3.0 soon. Please reopen this issue if you still have this problem.

Have a nice day!

**Comment by cmaster11** [comment]
Thanks a lot!

**Comment by Prnyself** [comment]
> Thanks a lot!

v2.3.0 has just been released, please update your `go.mod` for this new version.

Have fun~
